/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CreateVoiceProjectArgs = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const ProjectId = IDL.Nat;
export const CloneStatus = IDL.Variant({
  'pending' : IDL.Null,
  'processing' : IDL.Null,
  'ready' : IDL.Null,
  'failed' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const VoiceId = IDL.Text;
export const VoiceProjectView = IDL.Record({
  'id' : ProjectId,
  'status' : CloneStatus,
  'lastUsedAt' : IDL.Opt(Timestamp),
  'owner' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'elevenLabsVoiceId' : IDL.Opt(VoiceId),
});
export const SynthesisId = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const SynthesisSettings = IDL.Record({
  'stability' : IDL.Float64,
  'style' : IDL.Float64,
  'similarityBoost' : IDL.Float64,
});
export const SynthesisRecordView = IDL.Record({
  'id' : SynthesisId,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'audioBlob' : ExternalBlob,
  'settings' : SynthesisSettings,
  'projectId' : ProjectId,
});
export const VoiceSample = IDL.Record({
  'id' : IDL.Nat,
  'owner' : UserId,
  'blob' : ExternalBlob,
  'filename' : IDL.Text,
  'projectId' : ProjectId,
  'uploadedAt' : Timestamp,
});
export const StartCloningArgs = IDL.Record({
  'sampleIds' : IDL.Vec(IDL.Nat),
  'projectId' : ProjectId,
});
export const SynthesizeSpeechArgs = IDL.Record({
  'text' : IDL.Text,
  'settings' : SynthesisSettings,
  'projectId' : ProjectId,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createVoiceProject' : IDL.Func(
      [CreateVoiceProjectArgs],
      [VoiceProjectView],
      [],
    ),
  'deleteVoiceProject' : IDL.Func([ProjectId], [IDL.Bool], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserApiKey' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getVoiceProject' : IDL.Func(
      [ProjectId],
      [IDL.Opt(VoiceProjectView)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listSynthesisRecords' : IDL.Func(
      [ProjectId],
      [IDL.Vec(SynthesisRecordView)],
      ['query'],
    ),
  'listVoiceProjects' : IDL.Func([], [IDL.Vec(VoiceProjectView)], ['query']),
  'listVoiceSamples' : IDL.Func([ProjectId], [IDL.Vec(VoiceSample)], ['query']),
  'registerClonedVoice' : IDL.Func(
      [ProjectId, IDL.Text],
      [VoiceProjectView],
      [],
    ),
  'setElevenLabsApiKey' : IDL.Func([IDL.Text], [], []),
  'setUserApiKey' : IDL.Func([IDL.Text], [], []),
  'startVoiceCloning' : IDL.Func([StartCloningArgs], [IDL.Text], []),
  'synthesizeSpeech' : IDL.Func(
      [SynthesizeSpeechArgs],
      [SynthesisRecordView],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'uploadVoiceSample' : IDL.Func(
      [ProjectId, IDL.Text, ExternalBlob],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CreateVoiceProjectArgs = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const ProjectId = IDL.Nat;
  const CloneStatus = IDL.Variant({
    'pending' : IDL.Null,
    'processing' : IDL.Null,
    'ready' : IDL.Null,
    'failed' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const VoiceId = IDL.Text;
  const VoiceProjectView = IDL.Record({
    'id' : ProjectId,
    'status' : CloneStatus,
    'lastUsedAt' : IDL.Opt(Timestamp),
    'owner' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'elevenLabsVoiceId' : IDL.Opt(VoiceId),
  });
  const SynthesisId = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const SynthesisSettings = IDL.Record({
    'stability' : IDL.Float64,
    'style' : IDL.Float64,
    'similarityBoost' : IDL.Float64,
  });
  const SynthesisRecordView = IDL.Record({
    'id' : SynthesisId,
    'owner' : UserId,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'audioBlob' : ExternalBlob,
    'settings' : SynthesisSettings,
    'projectId' : ProjectId,
  });
  const VoiceSample = IDL.Record({
    'id' : IDL.Nat,
    'owner' : UserId,
    'blob' : ExternalBlob,
    'filename' : IDL.Text,
    'projectId' : ProjectId,
    'uploadedAt' : Timestamp,
  });
  const StartCloningArgs = IDL.Record({
    'sampleIds' : IDL.Vec(IDL.Nat),
    'projectId' : ProjectId,
  });
  const SynthesizeSpeechArgs = IDL.Record({
    'text' : IDL.Text,
    'settings' : SynthesisSettings,
    'projectId' : ProjectId,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createVoiceProject' : IDL.Func(
        [CreateVoiceProjectArgs],
        [VoiceProjectView],
        [],
      ),
    'deleteVoiceProject' : IDL.Func([ProjectId], [IDL.Bool], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserApiKey' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getVoiceProject' : IDL.Func(
        [ProjectId],
        [IDL.Opt(VoiceProjectView)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listSynthesisRecords' : IDL.Func(
        [ProjectId],
        [IDL.Vec(SynthesisRecordView)],
        ['query'],
      ),
    'listVoiceProjects' : IDL.Func([], [IDL.Vec(VoiceProjectView)], ['query']),
    'listVoiceSamples' : IDL.Func(
        [ProjectId],
        [IDL.Vec(VoiceSample)],
        ['query'],
      ),
    'registerClonedVoice' : IDL.Func(
        [ProjectId, IDL.Text],
        [VoiceProjectView],
        [],
      ),
    'setElevenLabsApiKey' : IDL.Func([IDL.Text], [], []),
    'setUserApiKey' : IDL.Func([IDL.Text], [], []),
    'startVoiceCloning' : IDL.Func([StartCloningArgs], [IDL.Text], []),
    'synthesizeSpeech' : IDL.Func(
        [SynthesizeSpeechArgs],
        [SynthesisRecordView],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'uploadVoiceSample' : IDL.Func(
        [ProjectId, IDL.Text, ExternalBlob],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };