/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CloneStatus = { 'pending' : null } |
  { 'processing' : null } |
  { 'ready' : null } |
  { 'failed' : string };
export interface CreateVoiceProjectArgs {
  'name' : string,
  'description' : string,
}
export type ExternalBlob = Uint8Array;
export type ProjectId = bigint;
export interface StartCloningArgs {
  'sampleIds' : Array<bigint>,
  'projectId' : ProjectId,
}
export type SynthesisId = bigint;
export interface SynthesisRecordView {
  'id' : SynthesisId,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'text' : string,
  'audioBlob' : ExternalBlob,
  'settings' : SynthesisSettings,
  'projectId' : ProjectId,
}
export interface SynthesisSettings {
  'stability' : number,
  'style' : number,
  'similarityBoost' : number,
}
export interface SynthesizeSpeechArgs {
  'text' : string,
  'settings' : SynthesisSettings,
  'projectId' : ProjectId,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VoiceId = string;
export interface VoiceProjectView {
  'id' : ProjectId,
  'status' : CloneStatus,
  'lastUsedAt' : [] | [Timestamp],
  'owner' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'elevenLabsVoiceId' : [] | [VoiceId],
}
export interface VoiceSample {
  'id' : bigint,
  'owner' : UserId,
  'blob' : ExternalBlob,
  'filename' : string,
  'projectId' : ProjectId,
  'uploadedAt' : Timestamp,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createVoiceProject' : ActorMethod<
    [CreateVoiceProjectArgs],
    VoiceProjectView
  >,
  'deleteVoiceProject' : ActorMethod<[ProjectId], boolean>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserApiKey' : ActorMethod<[], [] | [string]>,
  'getVoiceProject' : ActorMethod<[ProjectId], [] | [VoiceProjectView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listSynthesisRecords' : ActorMethod<[ProjectId], Array<SynthesisRecordView>>,
  'listVoiceProjects' : ActorMethod<[], Array<VoiceProjectView>>,
  'listVoiceSamples' : ActorMethod<[ProjectId], Array<VoiceSample>>,
  'registerClonedVoice' : ActorMethod<[ProjectId, string], VoiceProjectView>,
  'setElevenLabsApiKey' : ActorMethod<[string], undefined>,
  'setUserApiKey' : ActorMethod<[string], undefined>,
  'startVoiceCloning' : ActorMethod<[StartCloningArgs], string>,
  'synthesizeSpeech' : ActorMethod<[SynthesizeSpeechArgs], SynthesisRecordView>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'uploadVoiceSample' : ActorMethod<[ProjectId, string, ExternalBlob], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];