/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface VoiceSample {
    id: bigint;
    owner: UserId;
    blob: ExternalBlob;
    filename: string;
    projectId: ProjectId;
    uploadedAt: Timestamp;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Timestamp = bigint;
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type VoiceId = string;
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface VoiceProjectView {
    id: ProjectId;
    status: CloneStatus;
    lastUsedAt?: Timestamp;
    owner: UserId;
    name: string;
    createdAt: Timestamp;
    description: string;
    elevenLabsVoiceId?: VoiceId;
}
export type SynthesisId = bigint;
export interface StartCloningArgs {
    sampleIds: Array<bigint>;
    projectId: ProjectId;
}
export interface http_header {
    value: string;
    name: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type UserId = Principal;
export interface SynthesisRecordView {
    id: SynthesisId;
    owner: UserId;
    createdAt: Timestamp;
    text: string;
    audioBlob: ExternalBlob;
    settings: SynthesisSettings;
    projectId: ProjectId;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface SynthesizeSpeechArgs {
    text: string;
    settings: SynthesisSettings;
    projectId: ProjectId;
}
export type ProjectId = bigint;
export interface CreateVoiceProjectArgs {
    name: string;
    description: string;
}
export interface SynthesisSettings {
    stability: number;
    style: number;
    similarityBoost: number;
}
export type CloneStatus = {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "processing";
    processing: null;
} | {
    __kind__: "ready";
    ready: null;
} | {
    __kind__: "failed";
    failed: string;
};
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createVoiceProject(args: CreateVoiceProjectArgs): Promise<VoiceProjectView>;
    deleteVoiceProject(id: ProjectId): Promise<boolean>;
    getCallerUserRole(): Promise<UserRole>;
    getUserApiKey(): Promise<string | null>;
    getVoiceProject(id: ProjectId): Promise<VoiceProjectView | null>;
    isCallerAdmin(): Promise<boolean>;
    listSynthesisRecords(projectId: ProjectId): Promise<Array<SynthesisRecordView>>;
    listVoiceProjects(): Promise<Array<VoiceProjectView>>;
    listVoiceSamples(projectId: ProjectId): Promise<Array<VoiceSample>>;
    registerClonedVoice(projectId: ProjectId, elevenLabsVoiceId: string): Promise<VoiceProjectView>;
    setElevenLabsApiKey(key: string): Promise<void>;
    setUserApiKey(key: string): Promise<void>;
    startVoiceCloning(args: StartCloningArgs): Promise<string>;
    synthesizeSpeech(args: SynthesizeSpeechArgs): Promise<SynthesisRecordView>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    uploadVoiceSample(projectId: ProjectId, filename: string, blob: ExternalBlob): Promise<bigint>;
}
import type { CloneStatus as _CloneStatus, ExternalBlob as _ExternalBlob, ProjectId as _ProjectId, SynthesisId as _SynthesisId, SynthesisRecordView as _SynthesisRecordView, SynthesisSettings as _SynthesisSettings, Timestamp as _Timestamp, UserId as _UserId, UserRole as _UserRole, VoiceId as _VoiceId, VoiceProjectView as _VoiceProjectView, VoiceSample as _VoiceSample, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createVoiceProject(arg0: CreateVoiceProjectArgs): Promise<VoiceProjectView> {
        if (this.processError) {
            try {
                const result = await this.actor.createVoiceProject(arg0);
                return from_candid_VoiceProjectView_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVoiceProject(arg0);
            return from_candid_VoiceProjectView_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteVoiceProject(arg0: ProjectId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVoiceProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVoiceProject(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserApiKey(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserApiKey();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserApiKey();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVoiceProject(arg0: ProjectId): Promise<VoiceProjectView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVoiceProject(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVoiceProject(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listSynthesisRecords(arg0: ProjectId): Promise<Array<SynthesisRecordView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSynthesisRecords(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSynthesisRecords(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async listVoiceProjects(): Promise<Array<VoiceProjectView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVoiceProjects();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVoiceProjects();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async listVoiceSamples(arg0: ProjectId): Promise<Array<VoiceSample>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVoiceSamples(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVoiceSamples(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerClonedVoice(arg0: ProjectId, arg1: string): Promise<VoiceProjectView> {
        if (this.processError) {
            try {
                const result = await this.actor.registerClonedVoice(arg0, arg1);
                return from_candid_VoiceProjectView_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerClonedVoice(arg0, arg1);
            return from_candid_VoiceProjectView_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async setElevenLabsApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setElevenLabsApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setElevenLabsApiKey(arg0);
            return result;
        }
    }
    async setUserApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserApiKey(arg0);
            return result;
        }
    }
    async startVoiceCloning(arg0: StartCloningArgs): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.startVoiceCloning(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startVoiceCloning(arg0);
            return result;
        }
    }
    async synthesizeSpeech(arg0: SynthesizeSpeechArgs): Promise<SynthesisRecordView> {
        if (this.processError) {
            try {
                const result = await this.actor.synthesizeSpeech(arg0);
                return from_candid_SynthesisRecordView_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.synthesizeSpeech(arg0);
            return from_candid_SynthesisRecordView_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async uploadVoiceSample(arg0: ProjectId, arg1: string, arg2: ExternalBlob): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadVoiceSample(arg0, arg1, await to_candid_ExternalBlob_n28(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadVoiceSample(arg0, arg1, await to_candid_ExternalBlob_n28(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_CloneStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CloneStatus): CloneStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_SynthesisRecordView_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SynthesisRecordView): Promise<SynthesisRecordView> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_VoiceProjectView_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VoiceProjectView): VoiceProjectView {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
async function from_candid_VoiceSample_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VoiceSample): Promise<VoiceSample> {
    return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VoiceId]): VoiceId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VoiceProjectView]): VoiceProjectView | null {
    return value.length === 0 ? null : from_candid_VoiceProjectView_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProjectId;
    status: _CloneStatus;
    lastUsedAt: [] | [_Timestamp];
    owner: _UserId;
    name: string;
    createdAt: _Timestamp;
    description: string;
    elevenLabsVoiceId: [] | [_VoiceId];
}): {
    id: ProjectId;
    status: CloneStatus;
    lastUsedAt?: Timestamp;
    owner: UserId;
    name: string;
    createdAt: Timestamp;
    description: string;
    elevenLabsVoiceId?: VoiceId;
} {
    return {
        id: value.id,
        status: from_candid_CloneStatus_n12(_uploadFile, _downloadFile, value.status),
        lastUsedAt: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.lastUsedAt)),
        owner: value.owner,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        elevenLabsVoiceId: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.elevenLabsVoiceId))
    };
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SynthesisId;
    owner: _UserId;
    createdAt: _Timestamp;
    text: string;
    audioBlob: _ExternalBlob;
    settings: _SynthesisSettings;
    projectId: _ProjectId;
}): Promise<{
    id: SynthesisId;
    owner: UserId;
    createdAt: Timestamp;
    text: string;
    audioBlob: ExternalBlob;
    settings: SynthesisSettings;
    projectId: ProjectId;
}> {
    return {
        id: value.id,
        owner: value.owner,
        createdAt: value.createdAt,
        text: value.text,
        audioBlob: await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value.audioBlob),
        settings: value.settings,
        projectId: value.projectId
    };
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    owner: _UserId;
    blob: _ExternalBlob;
    filename: string;
    projectId: _ProjectId;
    uploadedAt: _Timestamp;
}): Promise<{
    id: bigint;
    owner: UserId;
    blob: ExternalBlob;
    filename: string;
    projectId: ProjectId;
    uploadedAt: Timestamp;
}> {
    return {
        id: value.id,
        owner: value.owner,
        blob: await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value.blob),
        filename: value.filename,
        projectId: value.projectId,
        uploadedAt: value.uploadedAt
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    processing: null;
} | {
    ready: null;
} | {
    failed: string;
}): {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "processing";
    processing: null;
} | {
    __kind__: "ready";
    ready: null;
} | {
    __kind__: "failed";
    failed: string;
} {
    return "pending" in value ? {
        __kind__: "pending",
        pending: value.pending
    } : "processing" in value ? {
        __kind__: "processing",
        processing: value.processing
    } : "ready" in value ? {
        __kind__: "ready",
        ready: value.ready
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SynthesisRecordView>): Promise<Array<SynthesisRecordView>> {
    return await Promise.all(value.map(async (x)=>await from_candid_SynthesisRecordView_n21(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VoiceProjectView>): Array<VoiceProjectView> {
    return value.map((x)=>from_candid_VoiceProjectView_n10(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VoiceSample>): Promise<Array<VoiceSample>> {
    return await Promise.all(value.map(async (x)=>await from_candid_VoiceSample_n26(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
